### ISSUE TITLE
get_mapswipe_data fails with "No such file or directory: 'no-imagery.jpeg'"

### ISSUE THREAD

**Issue by pwaller** [betatim/dreamview#1]
```
$ time python3 scripts/get_mapswipe_data.py 1
start fetching tiles
fetched 0 tiles
Traceback (most recent call last):
  File "scripts/get_mapswipe_data.py", line 130, in <module>
    fetch_tiles(project_id)
  File "scripts/get_mapswipe_data.py", line 100, in fetch_tiles
    fetch_tile(x, y, z, klass, prj_dir)
  File "scripts/get_mapswipe_data.py", line 35, in fetch_tile
    no_imagery_img = io.imread("no-imagery.jpeg")
  File "/home/pwaller/.local/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/pwaller/.local/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/home/pwaller/.local/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'no-imagery.jpeg'

real    0m54.727s
user    0m1.696s
sys 0m0.920s
```

**Comment by betatim** [comment]
D'oh. Fixed now.

**Comment by pwaller** [comment]
Appears fixed.
