### ISSUE TITLE
Connection timeout fetching images

### ISSUE THREAD

**Issue by pwaller** [betatim/dreamview#3]
```
$ python3 scripts/get_mapswipe_data.py 1
tart fetching tiles
fetched 0 tiles
fetched 10 tiles
fetched 20 tiles
fetched 30 tiles
fetched 40 tiles
fetched 50 tiles
fetched 60 tiles
fetched 70 tiles
fetched 80 tiles
fetched 90 tiles
Traceback (most recent call last):
  File "/home/pwaller/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/pwaller/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/pwaller/.local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/home/pwaller/.local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/pwaller/.local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/home/pwaller/.local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

**Comment by betatim** [comment]
To get tiles from Bing without violating their TOS you need an API key, then fetch a JSON resource which tells you the URL and crucially a parameter to add to that URL. Currently that code is hardcoded. So beyond "temporary" failure I think this means we need to actually implement that extra round trip.

Docs: https://msdn.microsoft.com/en-us/library/ff701716.aspx
